/////////////////////////////////////////////////////////////////////////////
// Name:        
// Purpose:     
// Author:      
// Modified by: 
// Created:     29/10/2006 21:08:30
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 29/10/2006 21:08:30

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface ""
#endif

/*!
 * Includes
 */

////@begin includes
#include "bamcontrol.h"
#include "odlistbox.h"
////@end includes


#define CMD_EDIT_SECTOR		1

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define ID_LISTBOX1 10001
#define ID_LISTBOX2 10002
#define SYMBOL_CBAMEDITOR_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CBAMEDITOR_TITLE _("BAM Editor")
#define SYMBOL_CBAMEDITOR_IDNAME ID_DIALOG
#define SYMBOL_CBAMEDITOR_SIZE wxSize(400, 300)
#define SYMBOL_CBAMEDITOR_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CBamEditor class declaration
 */

class CBamEditor: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CBamEditor )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CBamEditor( );
    CBamEditor( wxWindow* parent, wxWindowID id = SYMBOL_CBAMEDITOR_IDNAME, const wxString& caption = SYMBOL_CBAMEDITOR_TITLE, const wxPoint& pos = SYMBOL_CBAMEDITOR_POSITION, const wxSize& size = SYMBOL_CBAMEDITOR_SIZE, long style = SYMBOL_CBAMEDITOR_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CBAMEDITOR_IDNAME, const wxString& caption = SYMBOL_CBAMEDITOR_TITLE, const wxPoint& pos = SYMBOL_CBAMEDITOR_POSITION, const wxSize& size = SYMBOL_CBAMEDITOR_SIZE, long style = SYMBOL_CBAMEDITOR_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CBamEditor event handler declarations
	void OnFileSelected(wxCommandEvent& event);
	void OnClose(wxCloseEvent& event);
	void OnContextMenu(wxContextMenuEvent& event);
	void OnContextMenuEvent(wxCommandEvent& event);
////@end CBamEditor event handler declarations

////@begin CBamEditor member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CBamEditor member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

	void SetCbmImage(CCbmImageBase *image);
	void SetCbmCharset(byte* buffer, int nLength);
	void ReadCbmDirectory();
	CBamControl *GetBamControl();
	int GetFileSectors(CCbmDirectoryEntry *entry, DWORD **buffer);

////@begin CBamEditor member variables
    CBamControl* m_BamList;
    wxStaticText* m_trackSector;
    CODListBox* m_FileList;

private:
	CCbmImageBase *cbmImage;
	CCbmDirectory *cbmDir;
	byte *cbmCharset;
	int charsetLength;

////@end CBamEditor member variables
};

