
#include "cbmimager_id.h"


// new event type for odlistbox drags
DEFINE_EVENT_TYPE(wxEVT_ODLISTBOX_DRAG_EVENT)
DEFINE_EVENT_TYPE(wxEVT_ODLISTBOX_SELECTION_EVENT)


BEGIN_DECLARE_EVENT_TYPES()
	DECLARE_EVENT_TYPE(wxEVT_ODLISTBOX_DRAG_EVENT, wxID_ANY)
	DECLARE_EVENT_TYPE(wxEVT_ODLISTBOX_SELECTION_EVENT, wxID_ANY)
END_DECLARE_EVENT_TYPES()


