/////////////////////////////////////////////////////////////////////////////
// Name:        
// Purpose:     
// Author:      
// Modified by: 
// Created:     28/10/2006 16:38:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/10/2006 16:38:48

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface ""
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define ID_TEXTCTRLPATH 10001
#define ID_BUTTONSELECTPATH 10002
#define ID_TEXTCTRLSEARCH 10003
#define ID_CBEXACTSEARCH 10004
#define ID_BUTTONSEARCH 10006
#define ID_LISTBOXRESULTS 10005
#define ID_STATUSBAR1 10007
#define SYMBOL_CFILESEARCHER_STYLE wxCAPTION|wxCLOSE_BOX
#define SYMBOL_CFILESEARCHER_TITLE _("Dialog")
#define SYMBOL_CFILESEARCHER_IDNAME ID_DIALOG
#define SYMBOL_CFILESEARCHER_SIZE wxSize(600, 300)
#define SYMBOL_CFILESEARCHER_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CFileSearcher class declaration
 */

class CFileSearcher: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CFileSearcher )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CFileSearcher( );
    CFileSearcher( wxWindow* parent, wxWindowID id = SYMBOL_CFILESEARCHER_IDNAME, const wxString& caption = SYMBOL_CFILESEARCHER_TITLE, const wxPoint& pos = SYMBOL_CFILESEARCHER_POSITION, const wxSize& size = SYMBOL_CFILESEARCHER_SIZE, long style = SYMBOL_CFILESEARCHER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CFILESEARCHER_IDNAME, const wxString& caption = SYMBOL_CFILESEARCHER_TITLE, const wxPoint& pos = SYMBOL_CFILESEARCHER_POSITION, const wxSize& size = SYMBOL_CFILESEARCHER_SIZE, long style = SYMBOL_CFILESEARCHER_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CFileSearcher event handler declarations
    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTONSELECTPATH
    void OnButtonselectpathClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTONSEARCH
    void OnButtonsearchClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_LISTBOX_SELECTED event handler for ID_LISTBOXRESULTS
    void OnListboxresultsSelected( wxCommandEvent& event );

////@end CFileSearcher event handler declarations

////@begin CFileSearcher member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CFileSearcher member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

	wxString& GetSelectedFile();

////@begin CFileSearcher member variables
	wxButton *m_okButton;
    wxTextCtrl* m_searchFolder;
    wxTextCtrl* m_searchText;
    wxCheckBox* m_exactSearch;
    wxListBox* m_resultsList;
    wxStatusBar* m_statusBar;

	wxString m_selectedFile;
////@end CFileSearcher member variables
};

