/////////////////////////////////////////////////////////////////////////////
// Name:        
// Purpose:     
// Author:      
// Modified by: 
// Created:     29/10/2006 12:02:54
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 29/10/2006 12:02:54

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface ""
#endif

/*!
 * Includes
 */

////@begin includes
#include "hexcontrol.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define ID_HEXCONTROL_ITEM	10001
#define SYMBOL_CHEXEDITOR_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CHEXEDITOR_TITLE _("Hex Editor")
#define SYMBOL_CHEXEDITOR_IDNAME ID_DIALOG
#define SYMBOL_CHEXEDITOR_SIZE wxSize(400, 400)
#define SYMBOL_CHEXEDITOR_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CHexEditor class declaration
 */

class CHexEditor: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CHexEditor )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CHexEditor( );
    CHexEditor( wxWindow* parent, wxWindowID id = SYMBOL_CHEXEDITOR_IDNAME, const wxString& caption = SYMBOL_CHEXEDITOR_TITLE, const wxPoint& pos = SYMBOL_CHEXEDITOR_POSITION, const wxSize& size = SYMBOL_CHEXEDITOR_SIZE, long style = SYMBOL_CHEXEDITOR_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CHEXEDITOR_IDNAME, const wxString& caption = SYMBOL_CHEXEDITOR_TITLE, const wxPoint& pos = SYMBOL_CHEXEDITOR_POSITION, const wxSize& size = SYMBOL_CHEXEDITOR_SIZE, long style = SYMBOL_CHEXEDITOR_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CHexEditor member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CHexEditor member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

	CHexControl *GetHexControl();

////@begin CHexEditor member variables
private:
	CHexControl *m_hexControl;
////@end CHexEditor member variables
};

