/***************************************************************************
 *   Copyright (C) 2006 by T.Terhaar and C. Thelen                         *
 *   uncletom@users.berlios.de, baccy_drm@users.berlios.de                 *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// Generated by DialogBlocks (unregistered), 29/10/2006 12:02:54

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface ""
#endif

/*!
 * Includes
 */

////@begin includes
#include "hexcontrol.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define ID_HEXCONTROL_ITEM	10001
#define SYMBOL_CHEXEDITOR_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CHEXEDITOR_TITLE _("Hex Editor")
#define SYMBOL_CHEXEDITOR_IDNAME ID_DIALOG
#define SYMBOL_CHEXEDITOR_SIZE wxSize(400, 400)
#define SYMBOL_CHEXEDITOR_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CHexEditor class declaration
 */

class CHexEditor: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CHexEditor )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CHexEditor( );
    CHexEditor( wxWindow* parent, wxWindowID id = SYMBOL_CHEXEDITOR_IDNAME, const wxString& caption = SYMBOL_CHEXEDITOR_TITLE, const wxPoint& pos = SYMBOL_CHEXEDITOR_POSITION, const wxSize& size = SYMBOL_CHEXEDITOR_SIZE, long style = SYMBOL_CHEXEDITOR_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CHEXEDITOR_IDNAME, const wxString& caption = SYMBOL_CHEXEDITOR_TITLE, const wxPoint& pos = SYMBOL_CHEXEDITOR_POSITION, const wxSize& size = SYMBOL_CHEXEDITOR_SIZE, long style = SYMBOL_CHEXEDITOR_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CHexEditor member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CHexEditor member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

	CHexControl *GetHexControl();

////@begin CHexEditor member variables
private:
	CHexControl *m_hexControl;
////@end CHexEditor member variables
};

