/////////////////////////////////////////////////////////////////////////////
// Name:        
// Purpose:     
// Author:      
// Modified by: 
// Created:     27/10/2006 18:30:16
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/10/2006 18:30:16

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface ""
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RENAMEDISK 10000
#define ID_TEXTCTRL1 10001
#define ID_TEXTCTRL2 10002
#define SYMBOL_DIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_DIALOG_TITLE _("Dialog")
#define SYMBOL_DIALOG_IDNAME ID_RENAMEDISK
#define SYMBOL_DIALOG_SIZE wxSize(400, 300)
#define SYMBOL_DIALOG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * Dialog class declaration
 */

class CRenameDisk: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Dialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CRenameDisk( );
    CRenameDisk( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_IDNAME, const wxString& caption = SYMBOL_DIALOG_TITLE, const wxPoint& pos = SYMBOL_DIALOG_POSITION, const wxSize& size = SYMBOL_DIALOG_SIZE, long style = SYMBOL_DIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_IDNAME, const wxString& caption = SYMBOL_DIALOG_TITLE, const wxPoint& pos = SYMBOL_DIALOG_POSITION, const wxSize& size = SYMBOL_DIALOG_SIZE, long style = SYMBOL_DIALOG_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Dialog event handler declarations
////@end Dialog event handler declarations

////@begin Dialog member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Dialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Dialog member variables
    wxTextCtrl* m_DiskName;
    wxTextCtrl* m_DiskID;
////@end Dialog member variables
};

