/***************************************************************************
 *   Copyright (C) 2006 by T.Terhaar and C. Thelen                         *
 *   uncletom@users.berlios.de, baccy_drm@users.berlios.de                 *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// Generated by DialogBlocks (unregistered), 27/10/2006 18:30:16

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "renamedisk.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif


////@begin includes
#include "renamedisk.h"
////@end includes

////@begin XPM images

////@end XPM images

/*!
 * Dialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS( CRenameDisk, wxDialog )

/*!
 * Dialog event table definition
 */

BEGIN_EVENT_TABLE( CRenameDisk, wxDialog )

////@begin Dialog event table entries
////@end Dialog event table entries

END_EVENT_TABLE()

/*!
 * Dialog constructors
 */

CRenameDisk::CRenameDisk( )
{
    Init();
}

CRenameDisk::CRenameDisk( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * Dialog creator
 */

bool CRenameDisk::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin Dialog creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end Dialog creation
    return true;
}

/*!
 * Member initialisation 
 */

void CRenameDisk::Init()
{
////@begin Dialog member initialisation
    m_DiskName = NULL;
    m_DiskID = NULL;
////@end Dialog member initialisation
}
/*!
 * Control creation for Dialog
 */

void CRenameDisk::CreateControls()
{    
////@begin Dialog content construction
    // Generated by DialogBlocks, 27/10/2006 18:30:16 (unregistered)

    CRenameDisk* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer3, 0, 0, 0);

    wxStaticText* itemStaticText4 = new wxStaticText( itemDialog1, wxID_STATIC, _("Disk Name"), wxDefaultPosition, wxSize(60, -1), 0 );
    itemBoxSizer3->Add(itemStaticText4, 0, wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    m_DiskName = new wxTextCtrl( itemDialog1, ID_TEXTCTRL1, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer3->Add(m_DiskName, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer6 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer6, 0, 0, 0);

    wxStaticText* itemStaticText7 = new wxStaticText( itemDialog1, wxID_STATIC, _("Disk ID"), wxDefaultPosition, wxSize(60, -1), 0 );
    itemBoxSizer6->Add(itemStaticText7, 0, wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    m_DiskID = new wxTextCtrl( itemDialog1, ID_TEXTCTRL2, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer6->Add(m_DiskID, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer9 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxButton* itemButton10 = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton11 = new wxButton( itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);
	itemButton11->SetDefault();

////@end Dialog content construction
}

/*!
 * Should we show tooltips?
 */

bool CRenameDisk::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap CRenameDisk::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin Dialog bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end Dialog bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon CRenameDisk::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin Dialog icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end Dialog icon retrieval
}
