/***************************************************************************
 *   Copyright (C) 2006 by T.Terhaar and C. Thelen                         *
 *   uncletom@users.berlios.de, baccy_drm@users.berlios.de                 *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// Generated by DialogBlocks (unregistered), 16/10/2006 20:30:06

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "selectimage.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "selectimage.h"

////@begin XPM images
////@end XPM images

/*!
 * SelectImage type definition
 */

IMPLEMENT_DYNAMIC_CLASS( SelectImage, wxDialog )

/*!
 * SelectImage event table definition
 */

BEGIN_EVENT_TABLE( SelectImage, wxDialog )

////@begin SelectImage event table entries
////@end SelectImage event table entries

END_EVENT_TABLE()

/*!
 * SelectImage constructors
 */

SelectImage::SelectImage( )
{
    Init();
}

SelectImage::SelectImage( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * SelectImage creator
 */

bool SelectImage::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin SelectImage creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end SelectImage creation
    return true;
}

/*!
 * Member initialisation 
 */

void SelectImage::Init()
{
////@begin SelectImage member initialisation
    m_FileSelector = NULL;
////@end SelectImage member initialisation
}
/*!
 * Control creation for SelectImage
 */

void SelectImage::CreateControls()
{    
////@begin SelectImage content construction
    // Generated by DialogBlocks, 16/10/2006 22:26:16 (unregistered)

    SelectImage* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    m_FileSelector = new wxGenericDirCtrl( itemDialog1, ID_GENERICDIRCTRL, _T(""), wxDefaultPosition, wxDefaultSize, wxDIRCTRL_SHOW_FILTERS, _T("D64 Files (*.d64)|*.d64|DFI Files (*.dfi)|*.dfi|All files (*.*)|*.*"), 0 );
    itemBoxSizer2->Add(m_FileSelector, 1, wxEXPAND|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer4, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxButton* itemButton5 = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end SelectImage content construction
}

/*!
 * Should we show tooltips?
 */

bool SelectImage::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap SelectImage::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin SelectImage bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end SelectImage bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon SelectImage::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin SelectImage icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end SelectImage icon retrieval
}
