/////////////////////////////////////////////////////////////////////////////
// Name:        selectimage.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     16/10/2006 20:30:06
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/10/2006 20:30:06

#ifndef _SELECTIMAGE_H_
#define _SELECTIMAGE_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "selectimage.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/dirctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxGenericDirCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_SELECTIMAGE 10009
#define ID_GENERICDIRCTRL 10010
#define SYMBOL_SELECTIMAGE_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_SELECTIMAGE_TITLE _("Select Image")
#define SYMBOL_SELECTIMAGE_IDNAME ID_SELECTIMAGE
#define SYMBOL_SELECTIMAGE_SIZE wxDefaultSize
#define SYMBOL_SELECTIMAGE_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * SelectImage class declaration
 */

class SelectImage: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( SelectImage )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    SelectImage( );
    SelectImage( wxWindow* parent, wxWindowID id = SYMBOL_SELECTIMAGE_IDNAME, const wxString& caption = SYMBOL_SELECTIMAGE_TITLE, const wxPoint& pos = SYMBOL_SELECTIMAGE_POSITION, const wxSize& size = SYMBOL_SELECTIMAGE_SIZE, long style = SYMBOL_SELECTIMAGE_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_SELECTIMAGE_IDNAME, const wxString& caption = SYMBOL_SELECTIMAGE_TITLE, const wxPoint& pos = SYMBOL_SELECTIMAGE_POSITION, const wxSize& size = SYMBOL_SELECTIMAGE_SIZE, long style = SYMBOL_SELECTIMAGE_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin SelectImage event handler declarations

////@end SelectImage event handler declarations

////@begin SelectImage member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end SelectImage member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin SelectImage member variables
    wxGenericDirCtrl* m_FileSelector;
////@end SelectImage member variables
};

#endif
    // _SELECTIMAGE_H_
