#! /bin/bash
for file in *.tasm; do
# Julia says it's OK!
	temp=${file/\.tasm/.txt}
	dest=${file/\.tasm/.asm}
	[ -e $temp ] && rm $temp
	./TMPview -w 16 -i $file -o $temp >/dev/null
	unexpand -a $temp | sed -f _pc64.sed > $dest
	echo $file
	dreamass -o ${dest/\.asm/.prg} $dest
	if [ $? -lt 1 ]; then
		[ ! -e /tmp/pc64 ] && mkdir -p /tmp/pc64
		cp $dest /tmp/pc64/pc64-$dest
	fi
done

#TMPVIEW:
# - -o always in append mode?
# - -w BAH? (annoying when redirecting)
# - missed the last .bend
